### ISSUE TITLE
v5 broke colors

### ISSUE THREAD

**Issue by marvinroger** [jbucaran/clor#10]
I am on Windows, on v4 everything worked fine, on v5 however, the following:

```js
console.log(c`<inverse>Hey Ho, <bold>Lets Go!</bold></inverse>`)
```

Renders

```js
Hey Ho, Lets Go!undefinedundefined
```

**Comment by marvinroger** [comment]
(With node v7.3.0)

**Comment by jbucaran** [comment]
<img width="759" alt="screen shot 2017-01-17 at 21 33 06" src="https://cloud.githubusercontent.com/assets/56996/22020622/8f93e24c-dcfc-11e6-9f3e-aa8a1fc4199e.png">

Can't repro this on macOS.

But [see this](https://github.com/jbucaran/clor/blob/master/ansi.js#L39), maybe instead of 

```js
Object.keys(ansi).forEach(k => ansi[k] = hasColor() ? ansi[k] : [""])
```

this

```js
Object.keys(ansi).forEach(k => ansi[k] = hasColor() ? ansi[k] : ["", ""])
```

If you can go ahead and try that to see if it fixes the issue, that'd be great.

**Comment by marvinroger** [comment]
@jbucaran I tried and it does remove the `undefined` from the output. But I forgot to specify that there's no color, too (although color worked on v4).

**Comment by jbucaran** [comment]
@marvinroger Thanks! This helped me identify the problem. The undefinedundefined thing is fixed and color should be avail. on windows again.

**Comment by marvinroger** [comment]
Awesome! Thank you.
